import React from 'react';
import ReactMarkdown from 'react-markdown';

interface ReportViewProps {
  report: string;
  onNewAnalysis: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, onNewAnalysis }) => {
  const copyToClipboard = () => {
    navigator.clipboard.writeText(report);
  };

  const downloadReport = () => {
    const element = document.createElement('a');
    const file = new Blob([report], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `TWISTED_Strategy_${Date.now()}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="report-view glass-card p-6 h-full overflow-y-auto relative">
      <div className="watermark absolute top-4 right-4 opacity-10 pointer-events-none select-none">
        <span className="text-4xl font-bold rotate-12 block">TWISTED</span>
        <span className="text-xs font-mono block">VERIFIED SWARM ANALYSIS</span>
      </div>

      <div className="report-content prose prose-invert max-w-none">
        <ReactMarkdown>{report}</ReactMarkdown>
      </div>

      <div className="iron-trigger-footer mt-8 pt-6 border-t border-white/10">
        <div className="disclaimer bg-red-900/20 border border-red-500/30 p-4 rounded-lg mb-6">
          <h4 className="text-red-400 font-bold mb-2">⚖️ LEGAL DISCLAIMER</h4>
          <p className="text-sm text-red-200/70">
            This strategic report is generated by an AI swarm and does NOT constitute professional legal advice.
            All suggestions should be reviewed by a qualified attorney. By using these materials, you acknowledge
            that TWISTED is not liable for outcomes resulting from automated actions.
          </p>
        </div>

        <div className="report-actions flex gap-4">
          <button
            className="glass-button secondary"
            onClick={copyToClipboard}
          >
            Copy Markdown
          </button>
          <button
            className="glass-button secondary"
            onClick={downloadReport}
          >
            Download PDF
          </button>

          <button
            className="glass-button primary"
            onClick={() => {
              if (window.confirm("IRON TRIGGER: Are you sure you want to push this to Google Workspace? You acknowledge the risks outlined in the disclaimer.")) {
                onNewAnalysis();
              }
            }}
          >
            Push to Workspace
          </button>
        </div>
      </div>
    </div>
  );
};
