"""
Chronicle Scribe: Generates comprehensive case deliverables.
Professional documentation, emails, contact lists, and visuals.
"""

import json
from typing import Dict, List

from backend.agents.base_agent import BaseAgent
from backend.utils.google_workspace import WorkspaceClient


class ChronicleScribeAgent(BaseAgent):
    """
    Creates the Help Package:
    - Strategic Report (markdown)
    - Pre-written Emails
    - Contact List
    - Visual Diagrams (Mermaid)
    """

    def __init__(self, llm, memory):
        super().__init__(
            agent_name="Chronicle Scribe",
            codename="chronicle_scribe",
            profile_dir="chronicle_scribe",
            llm=llm,
            task_type="synthesis",
        )
        self.workspace = WorkspaceClient()

    async def push_to_workspace(self, case_id: str, report: str, emails: List[Dict]):
        """Push report to Docs and emails to Gmail drafts."""
        results = {"doc_id": None, "draft_ids": []}

        # 1. Push Report to Google Docs
        doc_id = await self.workspace.create_google_doc(
            title=f"TWISTED Strategic Report - Case {case_id}", markdown_content=report
        )
        results["doc_id"] = doc_id

        # 2. Push Emails to Gmail Drafts
        for email in emails:
            draft = await self.workspace.create_gmail_draft(
                subject=email.get("subject", "Case follow-up"),
                body=email.get("body", ""),
                to=email.get("send_to"),
            )
            if draft:
                results["draft_ids"].append(draft["id"])

        return results

    async def generate_strategic_report(self, case_id: str, outcome: Dict) -> str:
        """Generate comprehensive strategic report."""
        scenario = outcome.get("scenario", {})

        # Query case context
        context = await self.query_memory(
            query=f"case {case_id} entities timeline risks",
            collection="case_analysis",
            n_results=10,
        )

        # Build report sections
        report = f"""# Strategic Case Analysis

> **Generated**: {self._current_timestamp()}
> **Case ID**: {case_id}
> **Engine Confidence**: {outcome.get("convergence_score", 0) * 100:.1f}%

---

## Executive Summary

{scenario.get("description", "No description available")}

**Recommended Strategy**: {scenario.get("name", "Unnamed")}
**Confidence Level**: {scenario.get("confidence", 0) * 100:.1f}%
**Estimated Timeline**: {scenario.get("estimated_timeline", "Unknown")}
**Estimated Investment**: {scenario.get("estimated_cost", "Unknown")}

---

## Situation Analysis

### Key Entities
{self._format_entities(context)}

### Timeline of Events
{self._format_timeline(context)}

### Risk Assessment
{self._format_risks(context)}

---

## Recommended Strategy

### Overview
{scenario.get("description", "")}

### Implementation Steps
{self._format_steps(scenario.get("steps", []))}

### Resource Requirements
- **Time**: {scenario.get("estimated_timeline", "TBD")}
- **Financial**: {scenario.get("estimated_cost", "TBD")}
- **Emotional Energy**: {self._estimate_energy(scenario)}

### Risk Mitigation
{self._format_risks(scenario.get("risks", []))}

---

## Alternative Approaches

If the primary strategy proves unsuitable, consider:

{self._format_alternatives(outcome)}

---

## Success Metrics

Track these indicators to measure progress:

1. **Early Win**: {self._extract_early_win(scenario)}
2. **Milestone**: {self._extract_milestone(scenario)}
3. **End State**: {scenario.get("success_criteria", "Resolution achieved")}

---

*This analysis was generated by TWISTED Glass Engine through multi-agent debate and synthesis.*
"""
        return report

    async def generate_emails(self, case_id: str, outcome: Dict) -> List[Dict]:
        """Generate pre-written professional emails."""
        scenario = outcome.get("scenario", {})

        # Determine email types based on scenario
        email_types = self._determine_email_types(scenario)

        emails = []
        for email_type in email_types:
            email = await self._generate_email_template(
                case_id=case_id, email_type=email_type, scenario=scenario
            )
            emails.append(email)

        return emails

    async def _generate_email_template(
        self, case_id: str, email_type: str, scenario: Dict
    ) -> Dict:
        """Generate specific email template."""

        prompts = {
            "legal_consultation": """Write an email to a lawyer requesting consultation.
Tone: Professional, urgent but not panicked.
Include: Brief case summary, desired outcome, request for initial meeting.""",
            "insurance_claim": """Write a formal insurance claim dispute letter.
Tone: Firm, factual, legally aware.
Include: Policy references, claim details, specific resolution requested.""",
            "counterparty": """Write to the opposing party proposing resolution.
Tone: Assertive but open to negotiation.
Include: Position summary, proposed terms, deadline for response.""",
            "regulatory_complaint": """Write a regulatory complaint (e.g., to state insurance commissioner).
Tone: Formal, detailed, citing specific violations.
Include: Timeline, evidence summary, requested regulatory action.""",
        }

        prompt = prompts.get(email_type, prompts["legal_consultation"])

        response = await self.llm.generate(
            contents=f"""{prompt}

Case Context: {scenario.get("description", "")}
Steps: {", ".join(scenario.get("steps", []))}

Generate subject line and body. Output JSON:
{{"subject": "...", "body": "...", "tone": "...", "send_to": "..."}}""",
            task_complexity="synthesis",
            response_mime_type="application/json",
        )

        return json.loads(response.text)

    async def extract_contacts(self, case_id: str, outcome: Dict) -> List[Dict]:
        """Extract and prioritize contact list."""
        # Query entities from memory
        entities = await self.query_memory(
            query="people organizations contact information",
            collection="case_analysis",
            n_results=20,
        )

        contacts = []
        for entity in entities:
            meta = entity.get("metadata", {})
            if meta.get("type") in ["entity_person", "entity_organization"]:
                contact = {
                    "name": meta.get("entity_data", {}).get("name", "Unknown"),
                    "role": meta.get("entity_data", {}).get("role", "Unknown"),
                    "organization": meta.get("entity_data", {}).get("organization", ""),
                    "priority": self._calculate_contact_priority(meta, outcome),
                    "contact_methods": self._infer_contact_methods(meta),
                    "context": entity.get("document", "")[:200],
                }
                contacts.append(contact)

        # Sort by priority
        contacts.sort(key=lambda x: x["priority"], reverse=True)
        return contacts

    async def generate_visuals(self, case_id: str, outcome: Dict) -> List[Dict]:
        """Generate Mermaid diagrams for case visualization."""
        visuals = []

        # Timeline diagram
        timeline_mermaid = await self._generate_timeline_diagram(case_id)
        visuals.append(
            {"type": "timeline", "format": "mermaid", "content": timeline_mermaid}
        )

        # Relationship map
        relationship_mermaid = await self._generate_relationship_diagram(case_id)
        visuals.append(
            {
                "type": "relationship_map",
                "format": "mermaid",
                "content": relationship_mermaid,
            }
        )

        # Strategy flowchart
        strategy_mermaid = await self._generate_strategy_flowchart(outcome)
        visuals.append(
            {"type": "strategy_flow", "format": "mermaid", "content": strategy_mermaid}
        )

        return visuals

    async def _generate_timeline_diagram(self, case_id: str) -> str:
        """Generate Mermaid Gantt chart of case timeline."""
        timeline_data = await self.query_memory(
            query="timeline events dates chronological",
            collection="case_analysis",
            n_results=15,
        )

        mermaid = "gantt\n    title Case Timeline\n    dateFormat YYYY-MM-DD\n    axisFormat %b %d\n"

        for item in timeline_data:
            meta = item.get("metadata", {})
            event = meta.get("event_data", {})
            date = event.get("date", "2024-01-01")
            name = event.get("event", "Unknown")[:30]
            mermaid += f"    {name} : milestone, {date}, 0d\n"

        return mermaid

    async def _generate_relationship_diagram(self, case_id: str) -> str:
        """Generate Mermaid graph of entity relationships."""
        relationship_data = await self.query_memory(
            query="relationships between people organizations",
            collection="case_analysis",
            n_results=20,
        )

        mermaid = "graph TD\n"

        nodes = set()
        for item in relationship_data:
            meta = item.get("metadata", {})
            rel = meta.get("relationship_data", {})
            source = rel.get("source", "Unknown")[:20]
            target = rel.get("target", "Unknown")[:20]
            rel_type = rel.get("type", "related")

            nodes.add(source)
            nodes.add(target)

            mermaid += f"    {source}[{source}] -->|{rel_type}| {target}[{target}]\n"

        return mermaid

    async def _generate_strategy_flowchart(self, outcome: Dict) -> str:
        """Generate Mermaid flowchart of recommended strategy."""
        scenario = outcome.get("scenario", {})
        steps = scenario.get("steps", [])

        mermaid = "flowchart TD\n"
        mermaid += (
            f"    Start([Begin]) --> Step1[{steps[0] if steps else 'Initiate'}]\n"
        )

        for i, step in enumerate(steps[1:], 2):
            prev = f"Step{i - 1}" if i > 1 else "Step1"
            current = f"Step{i}"
            mermaid += f"    {prev} --> {current}[{step}]\n"

        final_step = f"Step{len(steps)}" if len(steps) > 1 else "Step1"
        mermaid += f"    {final_step} --> Success([{scenario.get('success_criteria', 'Resolution')}])"

        return mermaid

    # Helper methods
    def _format_entities(self, context: List[Dict]) -> str:
        """Format entities for report."""
        lines = []
        for item in context[:5]:
            meta = item.get("metadata", {})
            if meta.get("type") == "entity_person":
                data = meta.get("entity_data", {})
                lines.append(
                    f"- **{data.get('name')}**: {data.get('role', 'Role unknown')}"
                )
        return "\n".join(lines) if lines else "No key entities identified."

    def _format_timeline(self, context: List[Dict]) -> str:
        """Format timeline for report."""
        events = []
        for item in context:
            meta = item.get("metadata", {})
            if meta.get("type") == "timeline_event":
                data = meta.get("event_data", {})
                events.append(f"- **{data.get('date')}**: {data.get('event')}")
        return (
            "\n".join(events[:8]) if events else "Timeline reconstruction incomplete."
        )

    def _format_risks(self, risks: List[Dict]) -> str:
        """Format risk list."""
        if not risks:
            return "No specific risks identified."
        lines = []
        for risk in risks:
            sev = risk.get("severity", 5)
            icon = "🔴" if sev > 7 else "🟡" if sev > 4 else "🟢"
            lines.append(
                f"{icon} **{risk.get('category', 'General')}** (Severity: {sev}/10): {risk.get('description', '')}"
            )
        return "\n".join(lines)

    def _format_steps(self, steps: List[str]) -> str:
        """Format implementation steps."""
        return "\n".join(f"{i + 1}. {step}" for i, step in enumerate(steps))

    def _estimate_energy(self, scenario: Dict) -> str:
        """Estimate emotional energy required."""
        steps = len(scenario.get("steps", []))
        risks = len(scenario.get("risks", []))
        score = steps + (risks * 2)

        if score > 15:
            return "High — sustained effort required, consider support system"
        elif score > 8:
            return "Moderate — periodic intensity, manageable with planning"
        else:
            return "Low — steady, predictable effort"

    def _format_alternatives(self, outcome: Dict) -> str:
        """Format alternative strategies."""
        return "Alternative strategies were evaluated during agent debate. The primary recommendation represents optimal balance of impact, feasibility, and risk."

    def _extract_early_win(self, scenario: Dict) -> str:
        """Extract early win metric."""
        steps = scenario.get("steps", [])
        return f"Completion of: {steps[0] if steps else 'Initial engagement'}"

    def _extract_milestone(self, scenario: Dict) -> str:
        """Extract milestone metric."""
        steps = scenario.get("steps", [])
        mid = len(steps) // 2
        return f"Completion of: {steps[mid] if steps else 'Midpoint review'}"

    def _calculate_contact_priority(self, meta: Dict, outcome: Dict) -> int:
        """Calculate priority score for contact."""
        # Simple scoring: mentioned in outcome = higher priority
        entity_data = meta.get("entity_data", {})
        role = entity_data.get("role", "").lower()

        score = 50  # Base

        if "lawyer" in role or "attorney" in role:
            score += 30
        if "insurance" in role:
            score += 25
        if "decision" in role or "manager" in role:
            score += 20

        return score

    def _infer_contact_methods(self, meta: Dict) -> List[str]:
        """Infer possible contact methods."""
        # In production, this would use entity resolution services
        return ["Email", "Phone"]  # Placeholder

    def _current_timestamp(self) -> str:
        """Current ISO timestamp."""
        from datetime import datetime

        return datetime.now().isoformat()
